# Generated by Django 4.1.6 on 2023-02-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.IntegerField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('order_id', models.IntegerField()),
                ('purchase_id', models.CharField(max_length=100)),
                ('csm_name', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('macaddr', models.CharField(max_length=100)),
            ],
        ),
    ]
